### ISSUE TITLE
Add multi-mode navigation

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#34]
**Is your feature request related to a problem? Please describe.**
horizontal / vertical navigation

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adiramardiani** [comment]
Hi @xiaoxian521 
First of all I want to thank you because this is the best implementation of element plus at the moment :)

My concern is the same, currently I have many menus with very deep levels up to 6 levels, and right now i'm really having a big problem with it


Other than the top menu, I think this should be used as a reference
![image](https://user-images.githubusercontent.com/8703419/133086205-bec9c15b-3713-4753-ac3a-519bce3abfc7.png)
If main menu is grouped by tab/icon like image above, I think the menu is more easy to understand, especially for application who have many module

You definitely know vben admin (sorry to discuss another theme in your issue),I think you can be a successor to vben for admin templates with element plus components, when he has entered the stable version and is ready to be used in production
![image](https://user-images.githubusercontent.com/8703419/133087188-caf4997c-d135-46ac-baec-409a64bca335.png)

besides the top menu, I hope you add this too (left menu mixed mode), this is perfect for complex menu and still look neatly arranged

I hope you use windicss too for css utility class

**Comment by adiramardiani** [comment]
Hi @xiaoxian521 
First of all I want to thank you because this is the best implementation of element plus at the moment :)

My concern is the same, currently I have many menus with very deep levels up to 6 levels, and right now i'm really having a big problem with it


Other than the top menu, I think this should be used as a reference
![image](https://user-images.githubusercontent.com/8703419/133086205-bec9c15b-3713-4753-ac3a-519bce3abfc7.png)
If main menu is grouped by tab/icon like image above, I think the menu is more easy to understand, especially for application who have many module

You definitely know vben admin (sorry to discuss another theme in your issue),I think you can be a successor to vben for admin templates with element plus components, when he has entered the stable version and is ready to be used in production
![image](https://user-images.githubusercontent.com/8703419/133087188-caf4997c-d135-46ac-baec-409a64bca335.png)

besides the top menu, I hope you add this too (left menu mixed mode), this is perfect for complex menu and still look neatly arranged

I hope you use windicss too for css utility class

**Comment by xiaoxian521** [comment]
I will consider adding left menu mixed mode, but windicss is more troublesome for the current post-maintenance, and it is not recommended to join windicss

**Comment by xiaoxian521** [comment]
As far as I know, it’s just hard to maintain for novices, of course you can use windicss in your project.

**Comment by xiaoxian521** [comment]
same issues: https://github.com/xiaoxian521/vue-pure-admin/issues/72
